spring:
  liquibase:
    change-log: classpath:/db/liquibase/db.changelog-master.xml
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    generate-unique-name: false
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
api:
  base:
    path: http://localhost:8080/login


